
export const ADD_CUSTOMER="ADD_CUSTOMER"
export const UPDATE_CUSTOMER="UPDATE_CUSTOMER"
export const DELETE_CUSTOMER="DELETE_CUSTOMER"


export const CHANGE_CATEGORY="CHANGE_CATEGORY"
export const GET_CATEGORIES_SUCCESS="GET_CATEGORIES_SUCCESS"

export const GET_CUSTOMERS="GET_CUSTOMERS"
export const GET_CUSTOMERS_SUCCESS="GET_CUSTOMERS_SUCCESS"
export const CREATE_CUSTOMERS_SUCCESS="CREATE_CUSTOMERS_SUCCESS"
export const UPDATE_CUSTOMERS_SUCCESS="UPDATE_CUSTOMERS_SUCCESS"